config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  root "posts#index"
  resources :posts do
    resource :like
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :likes, as: :record
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :record, polymorphic: true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, as: :record

  validates_presence_of :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_person_name

  has_many :posts, dependent: :destroy
  has_many :likes

  validates_presence_of :first_name, :last_name

  LIKE_LIMIT = 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include ActionView::RecordIdentifier
  def update
    if likes.exists?
      likes.destroy_all
    elsif current_user.likes.count < User::LIKE_LIMIT
      likes.first_or_create(user: current_user)
    else
      errors = "You've reached the like limit"
    end

    turbo_streams = [
      turbo_stream.replace("top-card", partial: "posts/top_card", locals: { name: current_user.name, remaining_likes_quantity: User::LIKE_LIMIT - current_user.likes.count, errors: errors } ),
      turbo_stream.replace(dom_id(resource), partial: "posts/#{resource_name}", locals: { "#{resource_name}".to_sym => resource })
    ]
    
    render turbo_stream: turbo_streams
  end

  private

  def likes
    @likes ||= resource.likes.where(user: current_user)
  end

  def resource
    post = Post.find(params[:post_id])
    @resource ||= if params[:comment_id]
                    post.comments.find(params[:comment_id])
                  else
                    post
                  end
  end

  def resource_name
    @resource_name ||= resource.class.name.downcase
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_comment.html.erb
<div class="comment my-4" id="<%= dom_id comment %>">
  <div class="row">
    <div class="col-auto">

      <!-- Avatar -->
      <a class="avatar avatar-sm" href="profile-posts.html">
        <% avatar_image_url = "assets/img/avatars/profiles/avatar-#{comment.user.id}.jpg" %>
        <img src="<%= avatar_image_url %>" alt="..." class="avatar-img rounded-circle">
      </a>

    </div>
    <div class="col ms-n2">

      <!-- Body -->
      <div class="comment-body py-0">

        <div class="row">
          <div class="col">

            <!-- Title -->
            <h5 class="comment-title">
              <%= comment.user.name %>
            </h5>

          </div>
        </div> <!-- / .row -->

        <!-- Text -->
        <p class="comment-text">
          <%= comment.body %>
        </p>

        <div>
          <!-- Likes -->
          <%= button_to post_like_path(comment.post, comment_id: comment.id), method: :patch, class: "btn btn-primary"  do %>
            <%= "#{comment.likes.where(user: current_user).exists? ? "👎 Unlike" : "👍 Like"}" %>
          <% end %>
        </div>
      </div>
    </div>
  </div> <!-- / .row -->
</div>

app/views/posts/_post.html.erb
<div class="card" id="<%= dom_id post %>">
  <div class="card-body">
    <!-- Header -->
    <div class="mb-3">
      <div class="row align-items-center">
        <div class="col-auto">
          <!-- Avatar -->
          <a href="#!" class="avatar">
            <% avatar_image_url = "assets/img/avatars/profiles/avatar-" + post.user.id.to_s + ".jpg" %>
            <img src="<%= avatar_image_url %>" alt="..." class="avatar-img rounded-circle">
          </a>
        </div>
        <div class="col ms-n2">

          <!-- Title -->
          <h4 class="mb-1">
            <%= post.user.name %>
          </h4>

        </div>
      </div> <!-- / .row -->
    </div>

    <!-- Text -->
    <p class="mb-3">
      <%= post.content %>
    </p>

    <!-- Buttons -->
    <div class="mb-3">
      <div class="row">
        <div class="col">
          <%= button_to post_like_path(post), method: :patch, class: "btn btn-primary"  do %>
            <%= "#{post.likes.where(user: current_user).exists? ? "👎 Unlike" : "👍 Like"}" %>
          <% end %>
        </div>
      </div>
    </div>

    <hr>
    <% post.comments.each do |comment| %>
      <%= render partial: 'posts/comment', locals: { comment: comment } %>
    <% end %>
  </div>
</div>

app/views/posts/_top_card.html.erb
<div id="top-card" class='mx-auto container row'>
  <div class='col-8'>
    <div class="card p-3">
      <h1 class="header-title">
        Hey <%= name %>,
      </h1>

      <!-- Subtitle -->
      <p class="header-subtitle">
        Read and like posts from your network
      </p>

      <div id="likes-count" class="h6">
        <span class="text-uppercase text-secondary">Remaining likes: </span>
        <%= remaining_likes_quantity %>
      </div>
      <%= tag.p errors if errors %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render partial: "top_card", locals: { name: current_user.name, remaining_likes_quantity: User::LIKE_LIMIT - current_user.likes.count, errors: nil } %>
<div class='mx-auto container row'>
  <div class='col-8'>
    <div class="timeline">
      <%= render partial: 'post', collection: @posts, as: :post, locals: { user: current_user } %>
    </div>
  </div>
</div>